/** 运算类积木 */
(function () {
  const C = '#40BF4A';
  BlockRegistry.registerCategory('operators', '运算', C);

  // 基础运算
  BlockRegistry.register({ type: 'op_add', category: 'operators', color: C, label: '{a} + {b}', labelKey: 'blocks.operators.op_add', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_sub', category: 'operators', color: C, label: '{a} - {b}', labelKey: 'blocks.operators.op_sub', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_mul', category: 'operators', color: C, label: '{a} × {b}', labelKey: 'blocks.operators.op_mul', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_div', category: 'operators', color: C, label: '{a} ÷ {b}', labelKey: 'blocks.operators.op_div', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_mod', category: 'operators', color: C, label: '{a} 取余 {b}', labelKey: 'blocks.operators.op_mod', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_pow', category: 'operators', color: C, label: '{a} 的 {b} 次方', labelKey: 'blocks.operators.op_pow', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: 2 }, { name: 'b', type: 'number', default: 3 }] });
  BlockRegistry.register({ type: 'op_random', category: 'operators', color: C, label: '在 {a} 到 {b} 间随机', labelKey: 'blocks.operators.op_random', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: 1 }, { name: 'b', type: 'number', default: 10 }] });
  BlockRegistry.register({ type: 'op_random_float', category: 'operators', color: C, label: '随机小数 (0~1)', labelKey: 'blocks.operators.op_random_float', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [] });

  // 比较
  BlockRegistry.register({ type: 'op_lt', category: 'operators', color: C, label: '{a} < {b}', labelKey: 'blocks.operators.op_lt', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_gt', category: 'operators', color: C, label: '{a} > {b}', labelKey: 'blocks.operators.op_gt', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_lte', category: 'operators', color: C, label: '{a} ≤ {b}', labelKey: 'blocks.operators.op_lte', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_gte', category: 'operators', color: C, label: '{a} ≥ {b}', labelKey: 'blocks.operators.op_gte', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_eq', category: 'operators', color: C, label: '{a} = {b}', labelKey: 'blocks.operators.op_eq', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'string', default: '' }, { name: 'b', type: 'string', default: '' }] });
  BlockRegistry.register({ type: 'op_neq', category: 'operators', color: C, label: '{a} ≠ {b}', labelKey: 'blocks.operators.op_neq', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'string', default: '' }, { name: 'b', type: 'string', default: '' }] });

  // 逻辑
  BlockRegistry.register({ type: 'op_and', category: 'operators', color: C, label: '{a} 且 {b}', labelKey: 'blocks.operators.op_and', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'boolean', default: false }, { name: 'b', type: 'boolean', default: false }] });
  BlockRegistry.register({ type: 'op_or', category: 'operators', color: C, label: '{a} 或 {b}', labelKey: 'blocks.operators.op_or', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'boolean', default: false }, { name: 'b', type: 'boolean', default: false }] });
  BlockRegistry.register({ type: 'op_not', category: 'operators', color: C, label: '非 {a}', labelKey: 'blocks.operators.op_not', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'boolean', default: false }] });

  // 字符串操作
  BlockRegistry.register({ type: 'op_join', category: 'operators', color: C, label: '连接 {a} 和 {b}', labelKey: 'blocks.operators.op_join', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'string', default: '苹果' }, { name: 'b', type: 'string', default: '香蕉' }] });
  BlockRegistry.register({ type: 'op_strlen', category: 'operators', color: C, label: '{s} 的长度', labelKey: 'blocks.operators.op_strlen', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: '' }] });
  BlockRegistry.register({ type: 'op_substr', category: 'operators', color: C, label: '{s} 从第 {start} 到第 {end} 个字符', labelKey: 'blocks.operators.op_substr', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'Hello' }, { name: 'start', type: 'number', default: 1 }, { name: 'end', type: 'number', default: 3 }] });
  BlockRegistry.register({ type: 'op_str_index', category: 'operators', color: C, label: '{s} 中 {sub} 的位置', labelKey: 'blocks.operators.op_str_index', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'Hello' }, { name: 'sub', type: 'string', default: 'l' }] });
  BlockRegistry.register({ type: 'op_str_contains', category: 'operators', color: C, label: '{s} 包含 {sub}?', labelKey: 'blocks.operators.op_str_contains', shape: 'boolean', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'Hello' }, { name: 'sub', type: 'string', default: 'ell' }] });
  BlockRegistry.register({ type: 'op_str_upper', category: 'operators', color: C, label: '{s} 转大写', labelKey: 'blocks.operators.op_str_upper', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'hello' }] });
  BlockRegistry.register({ type: 'op_str_lower', category: 'operators', color: C, label: '{s} 转小写', labelKey: 'blocks.operators.op_str_lower', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'HELLO' }] });
  BlockRegistry.register({ type: 'op_str_trim', category: 'operators', color: C, label: '{s} 去除空格', labelKey: 'blocks.operators.op_str_trim', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: '  hello  ' }] });
  BlockRegistry.register({ type: 'op_str_repeat', category: 'operators', color: C, label: '{s} 重复 {n} 次', labelKey: 'blocks.operators.op_str_repeat', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'ha' }, { name: 'n', type: 'number', default: 3 }] });
  BlockRegistry.register({ type: 'op_str_replace', category: 'operators', color: C, label: '{s} 将 {from} 替换为 {to}', labelKey: 'blocks.operators.op_str_replace', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'Hello World' }, { name: 'from', type: 'string', default: 'World' }, { name: 'to', type: 'string', default: 'Objector' }] });
  BlockRegistry.register({ type: 'op_char_at', category: 'operators', color: C, label: '{s} 的第 {n} 个字符', labelKey: 'blocks.operators.op_char_at', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: 'Hello' }, { name: 'n', type: 'number', default: 1 }] });
  BlockRegistry.register({ type: 'op_to_number', category: 'operators', color: C, label: '将 {s} 转为数字', labelKey: 'blocks.operators.op_to_number', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 's', type: 'string', default: '42' }] });
  BlockRegistry.register({ type: 'op_to_string', category: 'operators', color: C, label: '将 {n} 转为文本', labelKey: 'blocks.operators.op_to_string', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'n', type: 'number', default: 42 }] });

  // 数学函数
  BlockRegistry.register({ type: 'op_math', category: 'operators', color: C, label: '{fn} {n}', labelKey: 'blocks.operators.op_math', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'fn', type: 'dropdown', default: 'abs', options: ['abs', 'floor', 'ceil', 'round', 'sqrt', 'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'log', 'log2', 'exp', 'sign'] }, { name: 'n', type: 'number', default: 0 }] });
  BlockRegistry.register({ type: 'op_min', category: 'operators', color: C, label: '{a} 和 {b} 的最小值', labelKey: 'blocks.operators.op_min', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_max', category: 'operators', color: C, label: '{a} 和 {b} 的最大值', labelKey: 'blocks.operators.op_max', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: '' }, { name: 'b', type: 'number', default: '' }] });
  BlockRegistry.register({ type: 'op_clamp', category: 'operators', color: C, label: '将 {n} 限制在 {min} 到 {max} 之间', labelKey: 'blocks.operators.op_clamp', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'n', type: 'number', default: 5 }, { name: 'min', type: 'number', default: 0 }, { name: 'max', type: 'number', default: 10 }] });
  BlockRegistry.register({ type: 'op_lerp', category: 'operators', color: C, label: '从 {a} 到 {b} 插值 {t}', labelKey: 'blocks.operators.op_lerp', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [{ name: 'a', type: 'number', default: 0 }, { name: 'b', type: 'number', default: 100 }, { name: 't', type: 'number', default: 0.5 }] });
  BlockRegistry.register({ type: 'op_pi', category: 'operators', color: C, label: 'π', labelKey: 'blocks.operators.op_pi', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [] });
  BlockRegistry.register({ type: 'op_e', category: 'operators', color: C, label: 'e', labelKey: 'blocks.operators.op_e', shape: 'reporter', ports: { flowIn: false, flowOut: false }, params: [] });
})();
